env:
  browser: true
  es6: true
  node: true
extends: 'eslint:recommended'
installedESLint: true
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
rules:
  react/jsx-uses-vars: 2
  react/jsx-uses-react: 2
  no-console:
    - warn
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
