// NOTE: This file was most likely generated by AI and may contain errors.

import React, { useMemo, useRef } from "react"

import {
  CategoryScale,
  Chart as ChartJS,
  Legend,
  LineElement,
  LinearScale,
  PointElement,
  TimeScale,
  Title,
  Tooltip,
} from "chart.js"

import { Line } from "react-chartjs-2"
import "chartjs-adapter-date-fns"
import { enAU } from "date-fns/locale"
import {
  endOfDay,
  max as maxDate,
  startOfDay,
  subMonths,
  subYears,
} from "date-fns"
import zoomPlugin from "chartjs-plugin-zoom"

import type {
  ActiveElement,
  ChartData,
  ChartEvent,
  ChartOptions,
  FontSpec,
  InteractionOptions,
  LegendOptions,
  LinearScaleOptions,
  PluginOptionsByType,
  TimeScaleOptions,
  TooltipOptions,
} from "chart.js"

import type { BodyMetricDataPoint, TimeScaleOption } from "../types"

interface ZoomPluginOptions {
  pan?: {
    enabled?: boolean
    mode?: "x" | "y" | "xy"
    threshold?: number
    modifierKey?: "ctrl" | "alt" | "shift" | "meta" | null
  }
  zoom?: {
    wheel?: {
      enabled?: boolean
      speed?: number
      modifierKey?: "ctrl" | "alt" | "shift" | "meta" | null
    }
    drag?: { enabled?: boolean }
    pinch?: { enabled?: boolean }
    mode?: "x" | "y" | "xy"
    enabled?: boolean
  }
}

type BodyMetricsChartOptionsType = ChartOptions<"line"> & {
  plugins?: PluginOptionsByType<"line"> & {
    zoom?: ZoomPluginOptions
    legend?: Partial<LegendOptions<"line">>
    tooltip?: Partial<TooltipOptions<"line">>
  }
  scales?: {
    x?: TimeScaleOptions
    yWeight?: LinearScaleOptions
    yFat?: LinearScaleOptions
    yWaist?: LinearScaleOptions
    // Allow other scales potentially added by plugins or future changes
    [key: string]: any // Allow additional scale definitions if necessary
  }
  interaction?: Partial<InteractionOptions>
}

ChartJS.register(
  CategoryScale,
  LinearScale,
  PointElement,
  LineElement,
  Title,
  Tooltip,
  Legend,
  TimeScale,
  zoomPlugin,
)

// TODO: This should probably be moved to a useEffect
const styles = getComputedStyle(document.documentElement)
const chart1 = styles.getPropertyValue("--chart-1")
const chart2 = styles.getPropertyValue("--chart-2")
const chart3 = styles.getPropertyValue("--chart-3")

const COLORS = {
  weight: chart1,
  fat: chart2,
  waist: chart3,
}

interface VisibleLines {
  weight: boolean
  fat: boolean
  waist: boolean
}

interface BodyMetricsChartProps {
  data: BodyMetricDataPoint[]
  loading: boolean
  timeScale?: TimeScaleOption
  visibleLines?: VisibleLines
  selectedPoint?: BodyMetricDataPoint | null
  onPointSelect?: (dataPoint: BodyMetricDataPoint | null) => void
  className?: string
}

export const BodyMetricsChart: React.FC<BodyMetricsChartProps> = ({
  data,
  timeScale = "ALL",
  visibleLines = { weight: true, fat: true, waist: true },
  selectedPoint = null,
  onPointSelect,
  className = "",
}) => {
  const chartRef = useRef<ChartJS<
    "line",
    { x: number; y: number | null }[],
    number
  > | null>(null)
  const sortedData = [...data].sort(
    (a, b) => a.createdAt.getTime() - b.createdAt.getTime(),
  )

  const { chartData, chartOptions } = useMemo(() => {
    if (sortedData.length === 0) {
      const emptyChartData: ChartData<
        "line",
        { x: number; y: number | null }[],
        number
      > = { datasets: [] }
      const emptyChartOptions = {} as BodyMetricsChartOptionsType

      return { chartData: emptyChartData, chartOptions: emptyChartOptions }
    }

    const selectedIndex = selectedPoint
      ? sortedData.findIndex(
          p => p.createdAt.getTime() === selectedPoint.createdAt.getTime(),
        )
      : -1

    let minTs: number | undefined = undefined
    let maxTs: number | undefined = undefined
    const lastDataPointDate = sortedData[sortedData.length - 1]?.createdAt
    const firstDataPointDate = sortedData[0]?.createdAt

    if (timeScale !== "ALL") {
      const endDate = endOfDay(lastDataPointDate)

      maxTs = endDate.getTime()
      let startDate: Date

      switch (timeScale) {
        case "1M":
          startDate = subMonths(endDate, 1)
          break
        case "3M":
          startDate = subMonths(endDate, 3)
          break
        case "6M":
          startDate = subMonths(endDate, 6)
          break
        case "1Y":
          startDate = subYears(endDate, 1)
          break
        default:
          startDate = firstDataPointDate
      }
      minTs = maxDate([
        startOfDay(startDate),
        startOfDay(firstDataPointDate),
      ]).getTime()
    } else {
      minTs = startOfDay(firstDataPointDate).getTime()
      maxTs = endOfDay(lastDataPointDate).getTime()
    }

    const xPaddingDays = 2
    if (minTs && maxTs) {
      minTs = minTs - xPaddingDays * 24 * 60 * 60 * 1000
      maxTs = maxTs + xPaddingDays * 24 * 60 * 60 * 1000
    }

    let timeUnit: "day" | "week" | "month" | "year" = "day"

    if (minTs && maxTs) {
      const visibleDurationMs = maxTs - minTs
      const visibleDays = visibleDurationMs / (1000 * 60 * 60 * 24)

      if (visibleDays > 730) timeUnit = "year"
      else if (visibleDays > 180) timeUnit = "month"
      else if (visibleDays > 30) timeUnit = "week"
      else timeUnit = "day"
    }

    const createDataset = (
      key: keyof VisibleLines,
      label: string,
      yAxisID: string,
      color: string,
      dataExtractor: (p: BodyMetricDataPoint) => number | undefined | null,
    ) => {
      if (!visibleLines[key]) return null
      return {
        label: label,
        data: sortedData.map(point => ({
          x: point.createdAt.getTime(),
          y: dataExtractor(point) ?? null,
        })),
        borderColor: color,
        backgroundColor: color,
        tension: 0.3,
        // These two are effectively the same because there is a default radius
        // change somewhere else, possibly from the library itself.
        pointRadius: 2,
        pointHoverRadius: 2.5,
        // Changing the colour from transparent to a solid colour for selected
        // points works ok but there is no animation with this approach.
        // Using the radius size instead allows for a smooth transition but can
        // cause the chart to slightly adjust its scale when a point is
        // selected, which is not ideal.
        pointHoverBackgroundColor: ({ dataIndex }: { dataIndex: number }) => {
          return dataIndex === selectedIndex ? color : "transparent"
        },
        pointHoverBorderColor: ({ dataIndex }: { dataIndex: number }) => {
          return dataIndex === selectedIndex ? color : "transparent"
        },
        pointBackgroundColor: ({ dataIndex }: { dataIndex: number }) => {
          return dataIndex === selectedIndex ? color : "transparent"
        },
        pointBorderColor: ({ dataIndex }: { dataIndex: number }) => {
          return dataIndex === selectedIndex ? color : "transparent"
        },
        yAxisID: yAxisID,
        borderWidth: 2,
        spanGaps: true,
        parsing: false,
        borderCapStyle: "round",
      }
    }
    const datasets = [
      createDataset(
        "weight",
        "Weight (kg)",
        "yWeight",
        COLORS.weight,
        p => p.weight,
      ),
      createDataset("fat", "Fat %", "yFat", COLORS.fat, p => p.fat),
      createDataset(
        "waist",
        "Waist (cm)",
        "yWaist",
        COLORS.waist,
        p => p.waist,
      ),
    ].filter(Boolean)

    const chartDataConfig: ChartData<
      "line",
      { x: number; y: number | null }[],
      number
    > = {
      datasets: datasets as ChartData<
        "line",
        { x: number; y: number | null }[],
        number
      >["datasets"],
    }

    const chartOptionsConfig: ChartOptions = {
      responsive: true,
      maintainAspectRatio: false,
      interaction: {
        mode: "index",
        intersect: false,
        axis: "x",
        includeInvisible: false,
      },
      scales: {
        x: {
          type: "time",
          min: minTs,
          max: maxTs,
          time: {
            unit: timeUnit,
            tooltipFormat: "PPpp",
            displayFormats: {
              day: "d MMM",
              week: "d MMM yyyy",
              month: "MMM yyyy",
              year: "yyyy",
            },
            parser: undefined,
            round: "day",
            isoWeekday: false,
            minUnit: "millisecond",
          },
          title: {
            display: false,
            text: "Date",
            align: "center",
            color: undefined,
            font: {} as FontSpec,
            padding: 0,
          },
          grid: { display: false },
          ticks: {
            maxRotation: 0,
            autoSkip: true,
            autoSkipPadding: 15,
            maxTicksLimit: timeScale === "1M" ? 12 : 15,
            display: true,
            callback: value => {
              const date = new Date(value as number)

              return date.toLocaleDateString("en-AU", {
                day: "2-digit",
                month: "short",
                year:
                  timeScale === "ALL" || timeScale === "1Y"
                    ? "numeric"
                    : undefined,
              })
            },
            color: undefined,
            font: {} as FontSpec,
            major: {},
            padding: 3,
            stepSize: undefined,
          },
          adapters: { date: { locale: enAU } },
        },
        ...(visibleLines.weight && {
          yWeight: {
            display: false,
            type: "linear",
            position: "left",
            title: {
              display: true,
              text: "Weight (kg)",
              font: { size: 10 },
              color: COLORS.weight,
              align: "center",
              padding: 0,
            },
            grid: { display: false },
            ticks: { maxTicksLimit: 5, color: COLORS.weight },
            grace: "10%",
          },
        }),
        ...(visibleLines.fat && {
          yFat: {
            display: false,
            type: "linear",
            position: "right",
            title: {
              display: true,
              text: "Fat %",
              font: { size: 10 },
              color: COLORS.fat,
              align: "center",
              padding: 0,
            },
            grid: { drawOnChartArea: false },
            ticks: {
              callback: (value: number | string) => `${value}%`,
              maxTicksLimit: 5,
              color: COLORS.fat,
            },
            grace: "10%",
          },
        }),
        ...(visibleLines.waist && {
          yWaist: {
            display: false,
            type: "linear",
            position: "right",
            title: {
              display: true,
              text: "Waist (cm)",
              font: { size: 10 },
              color: COLORS.waist,
              align: "center",
              padding: 0,
            },
            grid: { drawOnChartArea: false },
            ticks: {
              callback: (value: number | string) => `${value} cm`,
              maxTicksLimit: 5,
              color: COLORS.waist,
            },
            grace: "10%",
          },
        }),
      },
      plugins: {
        legend: { display: false },
        tooltip: { enabled: false },
        zoom: {
          pan: { enabled: true, mode: "x", threshold: 5 },
          zoom: {
            wheel: { enabled: false, speed: 0.1 },
            drag: { enabled: false },
            pinch: { enabled: false },
            mode: "x",
          },
        },
      },
      onClick: (_event: ChartEvent, elements: ActiveElement[]) => {
        if (!onPointSelect) return
        const chart = chartRef.current

        if (elements.length > 0 && chart) {
          const { index } = elements[0]
          const clickedDataPoint = sortedData[index]

          const selectedPointTime = selectedPoint?.createdAt.getTime()
          const clickedPointTime = clickedDataPoint.createdAt.getTime()

          onPointSelect(
            selectedPointTime === clickedPointTime ? null : clickedDataPoint,
          )
        }
      },
      animation: {
        duration: 500,
        easing: "easeOutQuad",
      },
    }

    return { chartData: chartDataConfig, chartOptions: chartOptionsConfig }

    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [sortedData, timeScale, visibleLines, selectedPoint])

  return (
    <div className={`relative ${className} min-h-48`}>
      {chartData.datasets.length > 0 ? (
        <Line ref={chartRef} data={chartData} options={chartOptions as any} />
      ) : (
        <p className="text-muted-foreground absolute flex h-full w-full items-center justify-center">
          No data yet
        </p>
      )}
    </div>
  )
}
